name: ossrh

on:
  push:
    tags:
      - jdependency-*

jobs:
  ossrh:
    runs-on: ubuntu-latest
    environment: maven-central
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Version
      uses: tcurdt/action-verify-version-maven@main

    - name: Setup Maven Central
      uses: actions/setup-java@v3
      with: # overwrite settings.xml
        distribution: 'zulu'
        java-version: 16
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Publish to Maven Central
      run: mvn -B -Prelease --file pom.xml deploy
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
